resources:
  Resources:
    IoTRuleRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: IoTToLambdaRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: iot.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: IoTInvokeLambda
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource:
                    - arn:aws:lambda:us-east-1:598858048125:function:todo-dev-*
