service: todo-resources

provider:
  name: aws
  runtime: python3.11
  region: us-east-1

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: TodosNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
#          - AttributeName: completed # Used for GSI (Global Secondary Index)
#            AttributeType: BOOL
        KeySchema:
          - AttributeName: id
            KeyType: HASH
#        GlobalSecondaryIndexes:
#          -IndexName: CompletedTaskIndex
#          KeySchema:
#             - AttributeName: completed
#               KeyType: HASH
#          Projection:
#            ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    WebSocketConnections:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: TodoWebSocketNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH

    # Standard Queue
    TodoQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: TodoQueueNew

    # FIFO Queue
    TodoFIFOQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: TodoQueue.fifo
        FifoQueue: true
        ContentBasedDuplication: false
        VisibilityTimeout: 30 # Lambda should complete execution in 30 seconds
        MessageRetentionPeriod: 345600 # Retain messages for 4 days
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt TodoDeadLetterQueue.Arn
          maxReceiveCount: 5 # Move to DLQ after 5 failed attempts

    # DLQ
    TodoDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: TodoDeadLetterQueue