service: todo-resources

provider:
  name: aws
  runtime: python3.11
  region: us-east-1

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: TodosNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
#          - AttributeName: completed # Used for GSI (Global Secondary Index)
#            AttributeType: BOOL
        KeySchema:
          - AttributeName: id
            KeyType: HASH
#        GlobalSecondaryIndexes:
#          -IndexName: CompletedTaskIndex
#          KeySchema:
#             - AttributeName: completed
#               KeyType: HASH
#          Projection:
#            ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    WebSocketConnections:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: TodoWebSocketNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH

    TodoQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: TodoQueueNew