# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cielowigle
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: todo-maria-training
# "service" is the name of this project. This will also be added to your AWS resource names.
service: todo

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  apiGateway:
    apiKeys:
      - todoApiKey
    usagePlan:
      quota:
        limit: 500 # Maximum 500 requests per month
        period: MONTH
      throttle:
        rateLimit: 5 # Max 5 requests per second
        burstLimit: 10 # Handles request spikes
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/TodoTable

layers:
  todoLayer:
    path: layers
    compatibleRuntimes:
      - python3.11
    description: "Lambda Layer for Python dependencies"

package:
  individually: true
  patterns:
    - '!venv/**'
    - '!node_modules/**'
    - 'node_modules/node-fetch/**'
    - '!package.json'
    - '!package-lock.json'
    - '!README.md'

functions:
  add_todo:
    handler: src/addTodo.add_todo
    layers:
      - arn:aws:lambda:us-east-1:598858048125:layer:todoLayer:1
    events:
      - http:
          path: todos
          method: post
          private: true
  get_todo:
    handler: src/getTodo.get_todo
    layers:
      - arn:aws:lambda:us-east-1:598858048125:layer:todoLayer:1
    events:
      - http:
          path: todos/{id}
          method: get
          private: true
  get_all_todo:
    handler: src/getAllTodo.get_all_todo
    layers:
      - arn:aws:lambda:us-east-1:598858048125:layer:todoLayer:1
    events:
      - http:
          path: todos
          method: get
          private: true
  update_todo:
    handler: src/updateTodo.update_todo
    layers:
      - arn:aws:lambda:us-east-1:598858048125:layer:todoLayer:1
    events:
      - http:
          path: todos/{id}
          method: put
          private: true
  delete:
    handler: src/deleteTodo.delete
    layers:
      - arn:aws:lambda:us-east-1:598858048125:layer:todoLayer:1
    events:
      - http:
          path: todos/{id}
          method: delete
          private: true

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
