service: todo-resources

provider:
  name: aws
  runtime: python3.11
  region: us-east-1

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: Todos
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    WebSocketConnections:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: TodoWebSocket
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH

    TodoQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: TodoQueue

outputs:
  todoTableArn:
    Value: !GetAtt TodoTable.Arn
    Export:
      Name: todoTableArn

  todoTableStreamArn:
    Value: !GetAtt TodoTable.StreamArn
    Export:
      Name: todoTableStreamArn

  webSocketConnectionsArn:
    Value: !GetAtt WebSocketConnections.Arn
    Export:
      Name: webSocketConnectionsArn

  todoQueueArn:
    Value: !GetAtt TodoQueue.Arn
    Export:
      Name: todoQueueArn
